"""Canonical immutable architecture configuration and builder registry."""

from .config import (
    ActivationConfig,
    ArchitectureConfig,
    ArchitectureLike,
    AttentionConfig,
    ContextConfig,
    ConvolutionConfig,
    GeometryConfig,
    ProgressiveDepthConfig,
    ResidualConfig,
    SequenceConfig,
    SpectralConfig,
    StateConfig,
    W0WarmupConfig,
    WaveConfig,
    architecture_to_mapping,
    normalize_activation_config,
    normalize_architecture,
    validate_architecture,
)
from .registry import (
    ArchitectureBuildRequest,
    ArchitectureBuildResult,
    ArchitectureCapabilities,
    ArchitectureLifecycle,
    available_architectures,
    build_architecture,
    get_architecture_builder,
    register_architecture,
)

__all__ = [
    "ActivationConfig",
    "ArchitectureConfig",
    "ArchitectureLike",
    "AttentionConfig",
    "ContextConfig",
    "ConvolutionConfig",
    "GeometryConfig",
    "ProgressiveDepthConfig",
    "ResidualConfig",
    "SequenceConfig",
    "SpectralConfig",
    "StateConfig",
    "W0WarmupConfig",
    "WaveConfig",
    "architecture_to_mapping",
    "normalize_activation_config",
    "normalize_architecture",
    "validate_architecture",
    "ArchitectureBuildRequest",
    "ArchitectureBuildResult",
    "ArchitectureCapabilities",
    "ArchitectureLifecycle",
    "available_architectures",
    "build_architecture",
    "get_architecture_builder",
    "register_architecture",
]
