"""Unified workplace task, model, data, registry, and training API."""

from __future__ import annotations

import importlib

__all__ = [
    "ACTIVATIONS",
    "ARTIFACT_FORMAT_VERSION",
    "ARTIFACT_MANIFEST_JSON_SCHEMA",
    "ArtifactChecksumError",
    "ArtifactError",
    "ArtifactExtensionError",
    "ArtifactFormatError",
    "ArtifactInfo",
    "ArtifactManifest",
    "ArtifactVersionError",
    "AcceleratorCapability",
    "BACKBONES",
    "BackboneProtocol",
    "BackboneRegistration",
    "CATEGORICAL_ENCODERS",
    "DROPOUTS",
    "DataSchema",
    "BackgroundPolicyError",
    "BackgroundSummary",
    "DifferentiableInferenceAdapter",
    "EXPLAINABLE_LAYERS",
    "ExplainabilityError",
    "ExplainabilityUnavailableError",
    "ExplainerConfig",
    "ExplanationCapabilityError",
    "ExplanationDriftSummary",
    "ExplanationResult",
    "FeatureGroup",
    "PSANNExplainer",
    "FittedTaskAdapter",
    "InferenceConfig",
    "InferencePool",
    "InferenceResult",
    "InferenceRuntime",
    "InferenceSession",
    "IdentifierRegistry",
    "LegacyCheckpointTrustError",
    "LegacyCheckpointWarning",
    "LOSSES",
    "METRICS",
    "MISSING_VALUE_IMPUTERS",
    "ModelSpec",
    "ModelSpecContract",
    "NumpyShard",
    "NORMALIZATIONS",
    "OPTIMIZERS",
    "OperationalEvent",
    "OperationalHooks",
    "OperationalMetadataError",
    "PerformanceBaseline",
    "PerformanceRegression",
    "PerformanceReport",
    "RetentionPolicy",
    "SCHEDULERS",
    "SupervisedData",
    "StreamingSupervisedData",
    "TaskAdapter",
    "TaskKind",
    "TaskSpec",
    "TopKResult",
    "TorchModuleAdapter",
    "TrainingConfig",
    "TrainingRun",
    "adapt_module",
    "accelerator_capability",
    "accelerator_support_matrix",
    "canonical_dtype",
    "compare_performance",
    "create_model",
    "create_inference_runtime",
    "explain",
    "make_explainer",
    "DerivedExport",
    "DerivedExportError",
    "ExportCapability",
    "ExportNotSupportedError",
    "ExportReport",
    "evaluate_export_capabilities",
    "export_derived",
    "create_task_adapter",
    "export_model",
    "inspect_artifact",
    "is_model_artifact",
    "load_model",
    "load_runtime",
    "load_runtime_pool",
    "load_model_spec",
    "migrate_artifact",
    "migrate_legacy_checkpoint",
    "register_backbone",
    "register_metric",
    "register_schema_transform",
    "ARTIFACT_RESOLVERS",
    "load_registry_runtime",
    "register_artifact_resolver",
    "resolve_artifact",
    "preprocessing_contract",
    "fingerprint_data",
    "fingerprint_model",
    "list_explainable_layers",
    "load_explainer_config",
    "register_explainable_layer",
    "save_explainer_config",
    "summarize_background",
    "summarize_explanation_drift",
    "write_explanation_report",
    "save_spec",
    "numpy_shard_stream",
    "redact_sensitive",
    "resolve_workplace_device",
    "runtime_accelerator_evidence",
    "sensitive_paths",
    "train",
    "train_streaming",
    "validate_no_secrets",
]

_LAZY_ATTRS = {
    "AcceleratorCapability": ".accelerators",
    "accelerator_capability": ".accelerators",
    "accelerator_support_matrix": ".accelerators",
    "canonical_dtype": ".accelerators",
    "resolve_workplace_device": ".accelerators",
    "runtime_accelerator_evidence": ".accelerators",
    "ARTIFACT_FORMAT_VERSION": ".artifact_schema",
    "ARTIFACT_MANIFEST_JSON_SCHEMA": ".artifact_schema",
    "ArtifactChecksumError": ".artifact_schema",
    "ArtifactError": ".artifact_schema",
    "ArtifactExtensionError": ".artifact_schema",
    "ArtifactFormatError": ".artifact_schema",
    "ArtifactVersionError": ".artifact_schema",
    "LegacyCheckpointTrustError": ".artifact_schema",
    "ArtifactInfo": ".artifacts",
    "LegacyCheckpointWarning": ".artifacts",
    "export_model": ".artifacts",
    "inspect_artifact": ".artifacts",
    "is_model_artifact": ".artifacts",
    "load_model": ".artifacts",
    "migrate_artifact": ".artifacts",
    "migrate_legacy_checkpoint": ".artifacts",
    "ArtifactManifest": ".contracts",
    "BackboneProtocol": ".contracts",
    "InferenceResult": ".contracts",
    "ModelSpecContract": ".contracts",
    "TaskAdapter": ".contracts",
    "TaskKind": ".contracts",
    "DataSchema": ".specs",
    "InferenceConfig": ".specs",
    "ModelSpec": ".specs",
    "TaskSpec": ".specs",
    "TopKResult": ".contracts",
    "TrainingConfig": ".specs",
    "load_model_spec": ".specs",
    "save_spec": ".specs",
    "FittedTaskAdapter": ".tasks",
    "create_task_adapter": ".tasks",
    "TorchModuleAdapter": ".module_adapter",
    "InferenceRuntime": ".inference",
    "InferencePool": ".inference",
    "InferenceSession": ".inference",
    "create_inference_runtime": ".inference",
    "load_runtime": ".inference",
    "load_runtime_pool": ".inference",
    "ARTIFACT_RESOLVERS": ".integrations",
    "load_registry_runtime": ".integrations",
    "register_artifact_resolver": ".integrations",
    "resolve_artifact": ".integrations",
    "DerivedExport": ".exports",
    "DerivedExportError": ".exports",
    "ExportCapability": ".exports",
    "ExportNotSupportedError": ".exports",
    "ExportReport": ".exports",
    "evaluate_export_capabilities": ".exports",
    "export_derived": ".exports",
    "preprocessing_contract": ".exports",
    "BackgroundPolicyError": ".explainability",
    "BackgroundSummary": ".explainability",
    "ExplainabilityError": ".explainability",
    "ExplainabilityUnavailableError": ".explainability",
    "ExplainerConfig": ".explainability",
    "ExplanationCapabilityError": ".explainability",
    "ExplanationDriftSummary": ".explainability",
    "ExplanationResult": ".explainability",
    "FeatureGroup": ".explainability",
    "PSANNExplainer": ".explainability",
    "explain": ".explainability",
    "load_explainer_config": ".explainability",
    "make_explainer": ".explainability",
    "save_explainer_config": ".explainability",
    "summarize_background": ".explainability",
    "summarize_explanation_drift": ".explainability",
    "write_explanation_report": ".explainability",
    "DifferentiableInferenceAdapter": ".explain_torch",
    "EXPLAINABLE_LAYERS": ".explain_torch",
    "list_explainable_layers": ".explain_torch",
    "register_explainable_layer": ".explain_torch",
    "OperationalEvent": ".operations",
    "OperationalHooks": ".operations",
    "OperationalMetadataError": ".operations",
    "RetentionPolicy": ".operations",
    "fingerprint_data": ".operations",
    "fingerprint_model": ".operations",
    "redact_sensitive": ".operations",
    "sensitive_paths": ".operations",
    "validate_no_secrets": ".operations",
    "PerformanceBaseline": ".performance",
    "PerformanceRegression": ".performance",
    "PerformanceReport": ".performance",
    "compare_performance": ".performance",
    "NumpyShard": ".streaming",
    "StreamingSupervisedData": ".streaming",
    "numpy_shard_stream": ".streaming",
    "train_streaming": ".streaming",
    "SupervisedData": ".lifecycle",
    "TrainingRun": ".lifecycle",
    "adapt_module": ".lifecycle",
    "create_model": ".lifecycle",
    "train": ".lifecycle",
    "ACTIVATIONS": ".registry",
    "BACKBONES": ".registry",
    "BackboneRegistration": ".registry",
    "CATEGORICAL_ENCODERS": ".registry",
    "DROPOUTS": ".registry",
    "IdentifierRegistry": ".registry",
    "LOSSES": ".registry",
    "METRICS": ".registry",
    "MISSING_VALUE_IMPUTERS": ".registry",
    "NORMALIZATIONS": ".registry",
    "OPTIMIZERS": ".registry",
    "SCHEDULERS": ".registry",
    "register_backbone": ".registry",
    "register_metric": ".registry",
    "register_schema_transform": ".registry",
}


def __getattr__(name: str):
    module_name = _LAZY_ATTRS.get(name)
    if module_name is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module = importlib.import_module(module_name, __name__)
    value = getattr(module, name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(set(globals()) | set(_LAZY_ATTRS))
