"""PSANN: Parameterized Sine-Activated Neural Networks.

Top-level package exports the primary-output sklearn estimators, expanders,
episodic trainers, and diagnostic utilities."""

from __future__ import annotations

import importlib

from ._version import __version__

__all__ = [
    "__version__",
    # Estimators
    "AttentionConfig",
    "PSANNClassifier",
    "PSANNRegressor",
    "ResPSANNRegressor",
    "ResConvPSANNRegressor",
    "SGRPSANNRegressor",
    "WaveResNetRegressor",
    "GeoSparseRegressor",
    # Expanders / activation configs
    "LSM",
    "LSMExpander",
    "LSMConv2d",
    "LSMConv2dExpander",
    "SineParam",
    "SigmoidParam",
    "ReLUSigmoidPSANN",
    "ActivationConfig",
    "StateConfig",
    "StateController",
    "ensure_state_config",
    "TrainingEvent",
    "TrainingCheckpointError",
    "ArtifactError",
    "ArtifactChecksumError",
    "ArtifactFormatError",
    "ArtifactVersionError",
    "ArtifactExtensionError",
    "ArtifactInfo",
    "LegacyCheckpointTrustError",
    "LegacyCheckpointWarning",
    "AcceleratorCapability",
    # Workplace lifecycle
    "TaskSpec",
    "ModelSpec",
    "TrainingConfig",
    "DataSchema",
    "InferenceConfig",
    "BackgroundPolicyError",
    "BackgroundSummary",
    "DifferentiableInferenceAdapter",
    "EXPLAINABLE_LAYERS",
    "ExplainabilityError",
    "ExplainabilityUnavailableError",
    "ExplainerConfig",
    "ExplanationCapabilityError",
    "ExplanationDriftSummary",
    "ExplanationResult",
    "FeatureGroup",
    "PSANNExplainer",
    "InferenceResult",
    "TopKResult",
    "InferencePool",
    "InferenceRuntime",
    "InferenceSession",
    "NumpyShard",
    "OperationalEvent",
    "OperationalHooks",
    "OperationalMetadataError",
    "PerformanceBaseline",
    "PerformanceRegression",
    "PerformanceReport",
    "RetentionPolicy",
    "StreamingSupervisedData",
    "TrainingRun",
    "SupervisedData",
    "TorchModuleAdapter",
    "create_model",
    "accelerator_capability",
    "accelerator_support_matrix",
    "canonical_dtype",
    "compare_performance",
    "create_inference_runtime",
    "explain",
    "make_explainer",
    "train",
    "load_model",
    "load_runtime",
    "load_runtime_pool",
    "inspect_artifact",
    "is_model_artifact",
    "migrate_artifact",
    "migrate_legacy_checkpoint",
    "adapt_module",
    "register_backbone",
    "register_metric",
    "register_schema_transform",
    "register_artifact_resolver",
    "resolve_artifact",
    "load_registry_runtime",
    "DerivedExport",
    "DerivedExportError",
    "ExportCapability",
    "ExportNotSupportedError",
    "ExportReport",
    "evaluate_export_capabilities",
    "export_derived",
    "preprocessing_contract",
    "fingerprint_data",
    "fingerprint_model",
    "list_explainable_layers",
    "load_explainer_config",
    "register_explainable_layer",
    "save_explainer_config",
    "summarize_background",
    "summarize_explanation_drift",
    "write_explanation_report",
    "numpy_shard_stream",
    "redact_sensitive",
    "resolve_workplace_device",
    "runtime_accelerator_evidence",
    "sensitive_paths",
    "train_streaming",
    "validate_no_secrets",
    "create_app",
    # Episodic training & rewards
    "EpisodeTrainer",
    "EpisodeConfig",
    "multiplicative_return_reward",
    "portfolio_log_return_reward",
    "make_episode_trainer_from_estimator",
    "HISSOOptions",
    "hisso_infer_series",
    "hisso_evaluate_reward",
    "RewardStrategyBundle",
    "FINANCE_PORTFOLIO_STRATEGY",
    "get_reward_strategy",
    "register_reward_strategy",
    # Token utilities
    "SimpleWordTokenizer",
    "SineTokenEmbedder",
    # Initialisation helpers
    "apply_siren_init",
    "siren_uniform_",
    # Core models
    "WaveResNet",
    "build_wave_resnet",
    "WaveEncoder",
    "WaveRNNCell",
    "scan_regimes",
    # Analysis utilities
    "jacobian_spectrum",
    "ntk_eigens",
    "participation_ratio",
    "mutual_info_proxy",
    "fit_linear_probe",
    "encode_and_probe",
    "make_context_rotating_moons",
    "make_drift_series",
    "make_shock_series",
    "make_regime_switch_ts",
    # Param utilities
    "count_params",
    "dense_mlp_params",
    "geo_sparse_net_params",
    "match_dense_width",
]

_LAZY_ATTRS = {
    # Estimator surfaces
    "AttentionConfig": ".attention",
    "PSANNClassifier": ".sklearn",
    "PSANNRegressor": ".sklearn",
    "ResPSANNRegressor": ".sklearn",
    "ResConvPSANNRegressor": ".sklearn",
    "SGRPSANNRegressor": ".sklearn",
    "WaveResNetRegressor": ".sklearn",
    "GeoSparseRegressor": ".sklearn",
    # Expanders / activation configs
    "LSM": ".lsm",
    "LSMExpander": ".lsm",
    "LSMConv2d": ".lsm",
    "LSMConv2dExpander": ".lsm",
    "SineParam": ".activations",
    "SigmoidParam": ".activations",
    "ReLUSigmoidPSANN": ".activations",
    "ActivationConfig": ".types",
    "StateConfig": ".state",
    "StateController": ".state",
    "ensure_state_config": ".state",
    "TrainingEvent": ".training_events",
    "TrainingCheckpointError": ".training_checkpoint",
    "ArtifactError": ".platform",
    "ArtifactChecksumError": ".platform",
    "ArtifactFormatError": ".platform",
    "ArtifactVersionError": ".platform",
    "ArtifactExtensionError": ".platform",
    "ArtifactInfo": ".platform",
    "LegacyCheckpointTrustError": ".platform",
    "LegacyCheckpointWarning": ".platform",
    "AcceleratorCapability": ".platform",
    # Workplace lifecycle
    "TaskSpec": ".platform",
    "ModelSpec": ".platform",
    "TrainingConfig": ".platform",
    "DataSchema": ".platform",
    "InferenceConfig": ".platform",
    "BackgroundPolicyError": ".platform",
    "BackgroundSummary": ".platform",
    "DifferentiableInferenceAdapter": ".platform",
    "EXPLAINABLE_LAYERS": ".platform",
    "ExplainabilityError": ".platform",
    "ExplainabilityUnavailableError": ".platform",
    "ExplainerConfig": ".platform",
    "ExplanationCapabilityError": ".platform",
    "ExplanationDriftSummary": ".platform",
    "ExplanationResult": ".platform",
    "FeatureGroup": ".platform",
    "PSANNExplainer": ".platform",
    "InferenceResult": ".platform",
    "TopKResult": ".platform",
    "InferencePool": ".platform",
    "InferenceRuntime": ".platform",
    "InferenceSession": ".platform",
    "NumpyShard": ".platform",
    "OperationalEvent": ".platform",
    "OperationalHooks": ".platform",
    "OperationalMetadataError": ".platform",
    "PerformanceBaseline": ".platform",
    "PerformanceRegression": ".platform",
    "PerformanceReport": ".platform",
    "RetentionPolicy": ".platform",
    "StreamingSupervisedData": ".platform",
    "TrainingRun": ".platform",
    "SupervisedData": ".platform",
    "TorchModuleAdapter": ".platform",
    "create_model": ".platform",
    "accelerator_capability": ".platform",
    "accelerator_support_matrix": ".platform",
    "canonical_dtype": ".platform",
    "compare_performance": ".platform",
    "create_inference_runtime": ".platform",
    "explain": ".platform",
    "make_explainer": ".platform",
    "train": ".platform",
    "load_model": ".platform",
    "load_runtime": ".platform",
    "load_runtime_pool": ".platform",
    "inspect_artifact": ".platform",
    "is_model_artifact": ".platform",
    "migrate_artifact": ".platform",
    "migrate_legacy_checkpoint": ".platform",
    "adapt_module": ".platform",
    "register_backbone": ".platform",
    "register_metric": ".platform",
    "register_schema_transform": ".platform",
    "register_artifact_resolver": ".platform",
    "resolve_artifact": ".platform",
    "load_registry_runtime": ".platform",
    "DerivedExport": ".platform",
    "DerivedExportError": ".platform",
    "ExportCapability": ".platform",
    "ExportNotSupportedError": ".platform",
    "ExportReport": ".platform",
    "evaluate_export_capabilities": ".platform",
    "export_derived": ".platform",
    "preprocessing_contract": ".platform",
    "fingerprint_data": ".platform",
    "fingerprint_model": ".platform",
    "list_explainable_layers": ".platform",
    "load_explainer_config": ".platform",
    "register_explainable_layer": ".platform",
    "save_explainer_config": ".platform",
    "summarize_background": ".platform",
    "summarize_explanation_drift": ".platform",
    "write_explanation_report": ".platform",
    "numpy_shard_stream": ".platform",
    "redact_sensitive": ".platform",
    "resolve_workplace_device": ".platform",
    "runtime_accelerator_evidence": ".platform",
    "sensitive_paths": ".platform",
    "train_streaming": ".platform",
    "validate_no_secrets": ".platform",
    "create_app": ".serving",
    # Episodic training & rewards
    "EpisodeTrainer": ".episodes",
    "EpisodeConfig": ".episodes",
    "multiplicative_return_reward": ".episodes",
    "portfolio_log_return_reward": ".episodes",
    "make_episode_trainer_from_estimator": ".episodes",
    "HISSOOptions": ".hisso",
    "hisso_infer_series": ".hisso",
    "hisso_evaluate_reward": ".hisso",
    "RewardStrategyBundle": ".rewards",
    "FINANCE_PORTFOLIO_STRATEGY": ".rewards",
    "get_reward_strategy": ".rewards",
    "register_reward_strategy": ".rewards",
    # Token utilities
    "SimpleWordTokenizer": ".tokenizer",
    "SineTokenEmbedder": ".embeddings",
    # Initialisation helpers
    "apply_siren_init": ".initializers",
    "siren_uniform_": ".initializers",
    # Core models
    "WaveResNet": ".models",
    "build_wave_resnet": ".models",
    "WaveEncoder": ".models",
    "WaveRNNCell": ".models",
    "scan_regimes": ".models",
    # Analysis utilities
    "jacobian_spectrum": ".utils",
    "ntk_eigens": ".utils",
    "participation_ratio": ".utils",
    "mutual_info_proxy": ".utils",
    "fit_linear_probe": ".utils",
    "encode_and_probe": ".utils",
    "make_context_rotating_moons": ".utils",
    "make_drift_series": ".utils",
    "make_shock_series": ".utils",
    "make_regime_switch_ts": ".utils",
    # Param utilities
    "count_params": ".params",
    "dense_mlp_params": ".params",
    "geo_sparse_net_params": ".params",
    "match_dense_width": ".params",
}


def __getattr__(name: str):
    module = _LAZY_ATTRS.get(name)
    if module is not None:
        try:
            mod = importlib.import_module(module, __name__)
        except Exception as exc:  # pragma: no cover - import-time optional deps
            raise ImportError(
                f"psann.{name} could not be imported from {module} (optional dependencies may be missing). "
                "Try installing extras like 'psann[sklearn]' or install 'psannlm' for LM tooling."
            ) from exc
        attr = getattr(mod, name)
        globals()[name] = attr
        return attr
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


def __dir__() -> list[str]:
    return sorted(list(globals().keys()) + list(_LAZY_ATTRS.keys()))
