checkpoints:
  best: "C:\\Users\\milin\\Documents\\psann\\runs\\hisso\\dense_cpu_smoke_dev\\dense_cpu_smoke_check\\checkpoints\\best.pt"
config_path: "C:\\Users\\milin\\Documents\\psann\\configs\\hisso\\dense_cpu_smoke.yaml"
data:
  test_shape:
    - 39
    - 4
  train_shape:
    - 115
    - 4
  val_shape:
    - 38
    - 4
estimator:
  params:
    batch_size: 48
    device: cpu
    epochs: 5
    hidden_layers: 1
    hidden_units: 32
    lr: 0.001
    random_state: 19
  target: psann.PSANNRegressor
hisso:
  amp_dtype: null
  enabled: true
  episodes_per_batch: 32
  mixed_precision: false
  primary_transform: softmax
  trans_cost: null
  transition_penalty: 0.0
  window: 24
output_dir: "C:\\Users\\milin\\Documents\\psann\\runs\\hisso\\dense_cpu_smoke_dev\\dense_cpu_smoke_check"
seed: 7
timestamp: "2025-10-30T10:10:46.979121"
