checkpoints:
  best: "C:\\Users\\milin\\Documents\\psann\\runs\\hisso\\wave_resnet_cpu_smoke\\checkpoints\\best.pt"
config_path: "C:\\Users\\milin\\Documents\\psann\\configs\\hisso\\wave_resnet_cpu_smoke.yaml"
data:
  test_shape:
    - 96
    - 4
    - 128
  train_shape:
    - 320
    - 4
    - 128
  val_shape:
    - 96
    - 4
    - 128
estimator:
  params:
    batch_size: 16
    data_format: channels_first
    device: cpu
    epochs: 15
    hidden_layers: 3
    hidden_units: 48
    lr: 0.0005
    preserve_shape: false
    progressive_depth_initial: 2
    progressive_depth_interval: 5
    random_state: 37
    w0_warmup_epochs: 5
  target: psann.WaveResNetRegressor
hisso:
  amp_dtype: null
  enabled: true
  episodes_per_batch: 32
  mixed_precision: false
  primary_transform: softmax
  trans_cost: null
  transition_penalty: 0.01
  window: 32
output_dir: "C:\\Users\\milin\\Documents\\psann\\runs\\hisso\\wave_resnet_cpu_smoke"
seed: 42
timestamp: "2025-10-29T06:11:36.541095"
